beacons/linux/uribeacon_advertise
default behavior wasn't changed
=> linux beacon: configurable dev interface for advertisement

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestAction.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestHelper.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/UriBeaconTests.java
Added the following actions:
* ADV_TX_POWER
* ADV_FLAGS
* ADV_URI
This are used to assert the values of the adv packet
=> Added ability to read adv packet.

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestAction.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestData.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestHelper.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestRunner.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestsAdapter.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/UriBeaconTests.java, android-uribeacon/uribeacon-validator/src/main/res/anim/rotation.xml, android-uribeacon/uribeacon-validator/src/main/res/drawable/executing.xml, android-uribeacon/uribeacon-validator/src/main/res/drawable/executing_animated.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/test_view.xml
In this pull request:
* Ability to validate adv packet. Which should be the most important test.
* Added tests for data, flags, lock and unlock
* Added timeout for scanning when testing
* No longer uses "wait" which was freezing the UI
* Added animation for when a test is running
=> Clean up, tests, animations

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/UriBeaconTests.java
Added the first 3 basic tests that all beacons should pass.
=> Basic tests

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/StartActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestData.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestRunner.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/UriBeaconTests.java, android-uribeacon/uribeacon-validator/src/main/res/values/strings.xml
Show dialog to ask if Lock/Unlock tests should be ran.
=> Add dialog to confirm optional characteristics

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/StartActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestAction.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestData.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestHelper.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestRunner.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestsAdapter.java
Nothing new. Just ran format on all files.
=> Code -> Reformat Code

android-uribeacon/uribeacon-validator/src/main/AndroidManifest.xml, android-uribeacon/uribeacon-validator/src/main/res/drawable/validator_icon.xml
=> Added icon

android-uribeacon/uribeacon-validator/README.md
Please review @scottjenson, @roywant and @schilit 
https://github.com/g-ortuno/uribeacon/blob/validator-readme/android-uribeacon/uribeacon-validator/README.md
=> Validator readme

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestRunner.java, android-uribeacon/uribeacon-validator/src/main/res/menu/tests_activity_actions.xml, android-uribeacon/uribeacon-validator/src/main/res/values/strings.xml
=> Share option

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/MultipleBeaconsAdapter.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestHelper.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestRunner.java, android-uribeacon/uribeacon-validator/src/main/res/drawable/list_divider.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/beacon_info_row.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/multiple_beacon_dialog.xml, android-uribeacon/uribeacon-validator/src/main/res/values/strings.xml
=> Dialog for when there are multiple UriBeacons

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/MultipleBeaconsAdapter.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestHelper.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestRunner.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestsAdapter.java
=> Single test

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/SpecUriBeaconTests.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestAction.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestData.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestHelper.java
Implemented the ability to test for multiple valid return codes.
=> Multiple valid error codes

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestRunner.java
Removed the wait between test where the 1s wait was unnecessary.
=> Tests run so much faster

specification/ConfigService.md
Please review @schilit and @roywant
=> Expanded lock return codes

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestActivity.java, android-uribeacon/uribeacon-validator/src/main/res/drawable/floating_button.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/activity_test.xml
=> Floating action button

android-uribeacon/uribeacon-library/src/main/java/org/uribeacon/beacon/UriBeacon.java, android-uribeacon/uribeacon-library/src/main/java/org/uribeacon/scan/compat/ScanRecord.java
=> Unhandled error in compat

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/CoreUriBeaconTests.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/MainActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/MultipleBeaconsAdapter.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/SpecUriBeaconTests.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestAction.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestActivity.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestData.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestHelper.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestRunner.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestTypesAdapter.java, android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestsAdapter.java, android-uribeacon/uribeacon-validator/src/main/res/anim/rotation.xml, android-uribeacon/uribeacon-validator/src/main/res/drawable/executing_animated.xml, android-uribeacon/uribeacon-validator/src/main/res/drawable/floating_button.xml, android-uribeacon/uribeacon-validator/src/main/res/drawable/lock_selector.xml, android-uribeacon/uribeacon-validator/src/main/res/drawable/validator_icon.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/activity_main.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/activity_test.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/beacon_info_row.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/list_subheader.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/lock_switch.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/multiple_beacon_dialog.xml, android-uribeacon/uribeacon-validator/src/main/res/layout/type_view.xml, android-uribeacon/uribeacon-validator/src/main/res/menu/main_activity_actions.xml, android-uribeacon/uribeacon-validator/src/main/res/menu/tests_activity_actions.xml, android-uribeacon/uribeacon-validator/src/main/res/values/dimens.xml, android-uribeacon/uribeacon-validator/src/main/res/values/styles.xml
All functions are now documented.
Added a couple of TODOs for anyone that wants to improve the code.
=> Added documentation and comments to the code

specification/ConfigService.md
Again, make is very clear how to calculate txpower value. Same as the
top level readme so a bit redundant but we’ve had too much trouble to
make SURE devs see this
=> More TxPower measurement help

specification/ConfigService.md, specification/README.md
Please review @roywant @schilit
=> Document update

android-uribeacon/android-uribeacon.iml, android-uribeacon/blescan/blescan.iml, android-uribeacon/uribeacon-library/uribeacon-library.iml, android-uribeacon/uribeacon-sample/uribeacon-sample.iml, android-uribeacon/uribeacon-validator/uribeacon-validator.iml
No real changes. The new version of android studio modified a some files.
=> Updates android studio does

ios-uribeacon/uribeacon/UBUriBeacon.m, ios-uribeacon/uribeacon/UBUriBeaconPrivate.h, ios-uribeacon/uribeacon/UBUriBeaconScanner.m
=> Added test implementation on iOS

android-uribeacon/uribeacon-library/src/main/java/org/uribeacon/beacon/UriBeacon.java
All tests pass. Please review @schilit
=> Fix bug in parseServiceDataFromBytes

android-uribeacon/uribeacon-library/src/main/java/org/uribeacon/beacon/UriBeacon.java
=> Added test implementation

ios-uribeacon/uribeacon/UBUriBeacon.m
=> Fixed discovery of test beacons

android-uribeacon/uribeacon-library/src/main/java/org/uribeacon/beacon/UriBeacon.java, android-uribeacon/uribeacon-sample/src/main/java/org/uribeacon/sample/UriBeaconScanActivity.java
@g-ortuno @matthewsibigtroth @scottjenson 
This is the second pull request to put Test Beacon scanning into the UriBeaocn app.
=> Scan for Test Service

ios-uribeacon/uribeacon/UBUriBeacon.m
=> Improved detection of test beacons

README.md
This was suggested by Paul Irish #224
=> Add example of trivial encoding

android-uribeacon/uribeacon-validator/src/main/java/org/uribeacon/validator/TestActivity.java
=> When there was no progress and multiple beacons no dialog was being shown

VENDORS.md
add alt attribute for screen reader accessibility
=> fix accessibility for image links
